spring.application.name=demo
#configuracion de la abse de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/motum_videos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=200MB

# Tamaño máximo de la request completa
spring.servlet.multipart.max-request-size=200MB
